import * as THREE from "three";
import { districtAt } from "../config.js?v=20261002-flight-sim-terrain";
import { WORLD_DEFINITION } from "../world/WorldDefinition.js?v=20261002-flight-sim-terrain";

const elementCache=new Map(),textCache=new Map();
const $=id=>{let element=elementCache.get(id);if(element===undefined){element=document.getElementById(id);elementCache.set(id,element??null);}return element;};
const setText=(id,value)=>{const text=String(value),element=$(id);if(element&&textCache.get(id)!==text){element.textContent=text;textCache.set(id,text);}};

export class HUD {
  constructor(graph,player,traffic,pedestrians,transit,incidents,weather,chunkManager=null,vehicleCollisions=null,rail=null,worldDefinition=WORLD_DEFINITION,police=null,airport=null){
    this.graph=graph;this.player=player;this.traffic=traffic;this.pedestrians=pedestrians;this.transit=transit;this.incidents=incidents;this.weather=weather;this.chunkManager=chunkManager;this.vehicleCollisions=vehicleCollisions;this.rail=rail;this.worldDefinition=worldDefinition;this.police=police;this.airport=airport;
    this.map=$("minimap");this.ctx=this.map.getContext("2d");this.lastFps=60;this.acc=0;this.frames=0;this.lastThrottleWidth="";this.incidentSignature="";this.lastMinimapMs=0;
    this.signalCount=0;this.roundaboutCount=0;for(const node of this.graph.nodes.values()){if(node.control==="signal")this.signalCount++;else if(node.control==="roundabout")this.roundaboutCount++;}
    this.staticMap=document.createElement("canvas");this.staticMap.width=this.map.width;this.staticMap.height=this.map.height;this.staticCtx=this.staticMap.getContext("2d");this.mapMode="";this.mapBounds=null;this.updateMapMode(true);
    document.querySelectorAll(".panel-tabs button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".panel-tabs button,.panel-content").forEach(element=>element.classList.remove("active"));btn.classList.add("active");$(btn.dataset.panel)?.classList.add("active");}));
    $("ground-service-stairs")?.addEventListener("click",()=>this.airport?.toggleGroundServiceForPlayer?.("stairs"));
    $("ground-service-jetway")?.addEventListener("click",()=>this.airport?.toggleGroundServiceForPlayer?.("jetway"));
  }

  mapModeForPlayer(){if(this.player.inAircraft)return"route";const island=this.worldDefinition.airports?.find(airport=>airport.kind==="island"),position=this.player.position;if(island&&Math.hypot(position.x-island.x,position.z-island.z)<2400)return"island";return"city";}
  updateMapMode(force=false){const mode=this.mapModeForPlayer();if(!force&&mode===this.mapMode)return;this.mapMode=mode;this.mapBounds=this.worldDefinition.mapRegions?.[mode]??this.worldDefinition.bounds;this.prepareMapTransform(this.mapBounds);this.drawStaticMap();}
  prepareMapTransform(bounds=this.worldDefinition.bounds){const padding=12,width=Math.max(1,bounds.maxX-bounds.minX),height=Math.max(1,bounds.maxZ-bounds.minZ),centre={x:(bounds.minX+bounds.maxX)*.5,z:(bounds.minZ+bounds.maxZ)*.5};this.mapScale=Math.min((this.map.width-padding*2)/width,(this.map.height-padding*2)/height);this.mapTranslateX=this.map.width/2-centre.x*this.mapScale;this.mapTranslateY=this.map.height/2-centre.z*this.mapScale;}
  beginWorldMap(context){context.save();context.translate(this.mapTranslateX,this.mapTranslateY);context.scale(this.mapScale,this.mapScale);}

  drawStaticMap(){
    const c=this.staticCtx,w=this.staticMap.width,h=this.staticMap.height,s=this.mapScale,definition=this.worldDefinition;c.clearRect(0,0,w,h);c.fillStyle="#091018";c.fillRect(0,0,w,h);this.beginWorldMap(c);
    const bounds=this.mapBounds??definition.bounds;c.strokeStyle="#23333d";c.lineWidth=1.2/s;c.strokeRect(bounds.minX,bounds.minZ,bounds.maxX-bounds.minX,bounds.maxZ-bounds.minZ);c.strokeStyle="#31404b";c.lineWidth=5/s;
    for(const road of this.graph.roads.values()){c.beginPath();for(let index=0;index<road.visualPoints.length;index++){const point=road.visualPoints[index];index?c.lineTo(point.x,point.z):c.moveTo(point.x,point.z);}c.stroke();}
    for(const node of this.graph.nodes.values()){if((node.connectedRoadIds?.length??0)<2)continue;if(node.control==="roundabout"){c.beginPath();c.arc(node.position.x,node.position.z,node.roundaboutRadius,0,Math.PI*2);c.stroke();c.beginPath();c.arc(node.position.x,node.position.z,node.roundaboutInnerRadius,0,Math.PI*2);c.stroke();}else{c.fillStyle="#26343d";c.beginPath();c.arc(node.position.x,node.position.z,Math.min(10,node.junctionRadius*.55),0,Math.PI*2);c.fill();}}
    if(this.rail){c.strokeStyle="#8b8667";c.lineWidth=2.2/s;const samples=180;for(const route of this.rail.routes??[this.rail.plan]){c.beginPath();const point=new THREE.Vector3();for(let index=0;index<=samples;index++){if(route.lookup)route.lookup.samplePosition(index/samples,point);else route.curve.getPointAt(index/samples,point);index?c.lineTo(point.x,point.z):c.moveTo(point.x,point.z);}c.stroke();}c.fillStyle="#d8c45c";for(const station of this.rail.plan.stations)c.fillRect(station.x-2.5/s,station.z-2.5/s,5/s,5/s);}
    if(this.airport){for(const airport of definition.airports??[definition.airport]){c.strokeStyle="#8bb9c4";c.lineWidth=1.4/s;c.strokeRect(airport.x-airport.perimeterHalfW,airport.z-airport.perimeterHalfD,airport.perimeterHalfW*2,airport.perimeterHalfD*2);c.fillStyle="#cfe8ef";c.textAlign="center";c.textBaseline="top";c.font=`600 ${9/s}px system-ui, sans-serif`;c.fillText(airport.code??airport.name,airport.x,airport.z+airport.perimeterHalfD+8/s);}}
    c.textAlign="center";c.textBaseline="bottom";c.font=`600 ${10/s}px system-ui, sans-serif`;for(const city of definition.cities){c.fillStyle="#8fd5e8";c.beginPath();c.arc(city.x,city.z,3.5/s,0,Math.PI*2);c.fill();c.fillStyle="#cfe8ef";c.fillText(city.name,city.x,city.z-6/s);}c.restore();
  }

  update(dt,simMs){
    this.acc+=dt;this.frames++;if(this.acc>.45){this.lastFps=Math.round(this.frames/this.acc);this.acc=0;this.frames=0;}
    const p=this.player,trainState=this.rail?.getPlayerState()??null,busState=this.transit?.getPlayerState?.()??null,airState=this.airport?.getPlayerState?.()??null,displayedSpeed=trainState?.speed??busState?.speed??airState?.speed??p.speed,pilotMode=Boolean(p.inAircraft&&airState?.pilot);
    setText("speed",Math.round(Math.abs(displayedSpeed)*(pilotMode?1.94384:3.6)));setText("speed-unit",pilotMode?`kt GS · ${Math.round(Math.abs(displayedSpeed)*3.6)} km/h`:"km/h");setText("gear",p.inTrain?(trainState?.passenger?"PAX":"HST"):p.inBus?"BUS":p.inAircraft?(airState?.pilot?"PILOT":"PAX"):!p.inVehicle?"—":p.speed<-.2?"R":Math.abs(p.speed)<.2?"P":"D");
    const nearLane=p.inTrain||p.inBus||p.inAircraft?null:(this.graph.lanes.get(p.nearestLaneId)??null),altitudeFt=Math.round((airState?.altitude??0)*3.28084),verticalFpm=Math.round((airState?.verticalSpeed??0)*196.85/50)*50;setText("road",p.inTrain?`Rail · ${trainState?.nextStation??"—"}`:p.inBus?`Bus ${busState?.line??"—"} · ${busState?.nextStop??"—"}`:pilotMode?`HDG ${String(Math.round(airState?.headingDeg??0)).padStart(3,"0")}° · ALT ${altitudeFt} ft`:p.inAircraft?`${airState?.originCode??"—"} → ${airState?.destinationCode??"—"}`:(nearLane?.roadId??"OFF ROAD"));setText("limit",p.inTrain?`${Math.round((trainState?.permittedSpeed??55.88)*3.6)}`:p.inBus?`${busState?.limit??30}`:pilotMode?`V/S ${verticalFpm>=0?"+":""}${verticalFpm} fpm`:p.inAircraft?"AIR":nearLane?`${nearLane.speedLimit}`:"—");setText("grip",p.inTrain?`${(trainState?.signalAspect??"RED").toUpperCase()} · P${trainState?.allocatedPlatform??"—"}`:p.inBus?`${busState?.passengers??0} ONBOARD`:pilotMode?`${airState?.stallWarning?"STALL · ":""}BANK ${Math.round(airState?.bankDeg??0)}° · AOA ${(airState?.aoaDeg??0).toFixed(1)}°`:p.inAircraft?`${(airState?.state??"flight").replaceAll("_"," ").toUpperCase()}`:`${Math.round(p.grip*100)}%`);
    const throttleWidth=`${Math.min(100,Math.abs(displayedSpeed)/(p.inTrain?55.88:p.inBus?25:50)*100)}%`,throttle=$("throttle-meter");if(throttle&&throttleWidth!==this.lastThrottleWidth){throttle.style.width=throttleWidth;this.lastThrottleWidth=throttleWidth;}
    const aircraftPower=airState?.pilot&&((airState?.reversePower??0)>.02)?`REV ${Math.round((airState.reversePower??0)*100)}%`:`THR ${Math.round((airState?.enginePower??airState?.throttle??0)*100)}%`;setText("mode",p.inTrain?(trainState?.passenger?`RIDING ${trainState.id} · WALKABLE CARRIAGE`:`${trainState?.spadWarning?"TRAIN PROTECTION ACTIVE · ":""}DRIVING ${trainState?.serviceId??"CLASS 43"} · ${trainState?.mode??"CAB"} CAMERA`):p.inBus?`RIDING BUS ${busState?.line??"—"} · ${busState?.mode??"WINDOW"} CAMERA`:p.inAircraft?(airState?.pilot?`FLYING ${airState?.id??"AIRCRAFT"} · ${airState?.cameraMode??"PILOT"} · ${aircraftPower} · BRK ${Math.round((airState?.brakePressure??0)*100)}% · FLAPS ${Math.round((airState?.flaps??0)*100)}% · GEAR ${(airState?.gear??1)>.5?"DOWN":"UP"}`:`RIDING ${airState?.id??"AIRCRAFT"} · ${airState?.originCode??"—"} → ${airState?.destinationCode??"—"}`):`${p.inVehicle?"DRIVING":"WALKING"} · ${p.cameraModes[p.cameraIndex]} CAMERA`);
    const groundServices=$("ground-services");if(groundServices)groundServices.hidden=!(pilotMode&&airState?.manual&&(airState?.altitude??Infinity)<1.5);if(pilotMode&&airState?.manual){const stairs=airState.groundServices?.stairs??{state:"UNAVAILABLE"},jetway=airState.groundServices?.jetway??{state:"UNAVAILABLE"};setText("ground-service-stairs-state",stairs.state);setText("ground-service-jetway-state",jetway.state);const stairsButton=$("ground-service-stairs"),jetwayButton=$("ground-service-jetway");if(stairsButton)stairsButton.title=stairs.reason??stairs.state;if(jetwayButton)jetwayButton.title=jetway.reason??jetway.state;}
    const focus=p.inTrain?this.rail.playerTrain?.headPosition:p.inBus?this.transit.playerBus?.mesh.position:p.inAircraft?this.airport?.getPlayerFocus?.()?.position:p.position,island=this.worldDefinition.airports?.find(airport=>airport.kind==="island"),onIsland=island&&Math.hypot((focus?.x??p.position.x)-island.x,(focus?.z??p.position.z)-island.z)<2200;setText("district",onIsland?"Merehaven Island":districtAt(focus?.x??p.position.x,focus?.z??p.position.z).name);setText("clock",this.weather.clockText());setText("weather",this.weather.mode.toUpperCase());setText("fps",`${this.lastFps} FPS`);
    let fullVehicles=0,lowVehicles=0,stoppedVehicles=0;for(const vehicle of this.traffic.vehicles){if(vehicle.renderTier==="full")fullVehicles++;else if(vehicle.renderTier==="low")lowVehicles++;if(vehicle.speed<1)stoppedVehicles++;}let visiblePedestrians=0;for(const agent of this.pedestrians.agents)if(agent.mesh.visible)visiblePedestrians++;
    setText("active-vehicles",`${fullVehicles} full · ${lowVehicles} low`);setText("distant-vehicles",this.traffic.distantDemand.toLocaleString());setText("ped-count",visiblePedestrians);setText("avg-speed",`${Math.round(this.traffic.averageSpeed)} km/h`);const stopped=stoppedVehicles/Math.max(1,this.traffic.vehicles.length);setText("congestion",stopped>.55?"SEVERE":stopped>.36?"HEAVY":stopped>.2?"MODERATE":"LOW");setText("punctuality",`${this.transit.punctuality}%`);setText("buses-at-stops",this.transit.busesAtStops);
    setText("active-trains",`${this.rail?.trains.length??0} Class 43 HST`);setText("rail-crossings",`${this.rail?.gradeSeparationCount??0} grade-separated · 0 level crossings`);setText("train-speed",`${Math.round(this.rail?.averageTrainSpeed??0)} km/h avg`);const railOps=this.rail?.getOperationsDiagnostics?.()??{};setText("rail-blocks",`${railOps.occupiedBlocks??0} occupied · ${railOps.reservedBlocks??0} reserved`);setText("rail-waiting",railOps.trainsWaitingAtSignals??0);setText("rail-junction-routes",railOps.activeJunctionRoutes??0);setText("rail-platforms",`${railOps.occupiedPlatforms??0} occupied · ${railOps.reservedPlatforms??0} reserved`);setText("rail-delay",`${Math.round(railOps.averageDelaySeconds??0)}s avg · ${railOps.mostDelayedService??"—"}`);setText("rail-dispatcher-time",`${(railOps.dispatcherUpdateMs??0).toFixed(2)} ms`);setText("rail-deadlocks",railOps.deadlockRecoveryCount??0);
    const policeState=this.police?.getState?.()??{wantedLevel:0,units:0,fines:0,licencePoints:0};setText("wanted-level",policeState.wantedLevel?`${"★".repeat(policeState.wantedLevel)} · ${policeState.units} units`:"CLEAR");setText("police-consequences",`£${policeState.fines} · ${policeState.licencePoints} points`);const airportState=this.airport?.getStats?.()??{aircraft:0,activeFlights:0,completedCycles:0};setText("airport-status",`${airportState.aircraft} aircraft · ${airportState.activeFlights} airborne`);setText("airport-cycles",airportState.completedCycles);setText("lane-changes",`${this.traffic.activeLaneChanges} active · ${this.traffic.completedLaneChanges} complete`);setText("collision-contacts",this.vehicleCollisions?.contacts??0);setText("steering-angle",`${THREE.MathUtils.radToDeg(this.player.steerAngle??0).toFixed(1)}°`);setText("routing-time",`${this.graph.lastRouteMs.toFixed(2)} ms`);setText("junction-controls",`${this.signalCount} signal · ${this.roundaboutCount} roundabout`);setText("sim-time",`${simMs.toFixed(2)} ms`);
    if(this.chunkManager){const chunks=this.chunkManager.getStats();setText("active-chunk",chunks.current);setText("preload-chunk",chunks.preload);setText("chunk-count",`${chunks.visible} full · ${chunks.preloaded} ready / ${chunks.cached}`);setText("chunk-neighbours",`${chunks.neighbours} local · ${chunks.ahead} ahead`);}
    this.renderIncidents();const start=performance.now();this.drawMap();this.lastMinimapMs=performance.now()-start;
  }

  renderIncidents(){const signature=this.incidents.incidents.map(incident=>`${incident.id}:${incident.status}:${Math.round(incident.age)}`).join("|");if(signature===this.incidentSignature)return;this.incidentSignature=signature;const element=$("incident-list");if(!element)return;if(!this.incidents.incidents.length){element.innerHTML='<p class="muted">No active incidents.</p>';return;}element.innerHTML=this.incidents.incidents.map(incident=>`<div class="incident"><strong>${incident.id} · ${incident.type}</strong><span>${incident.roadId} · ${incident.status} · ${Math.round(incident.age)}s</span></div>`).join("");}

  drawMap(){
    this.updateMapMode();const c=this.ctx,s=this.mapScale;c.clearRect(0,0,this.map.width,this.map.height);c.drawImage(this.staticMap,0,0);this.beginWorldMap(c);
    if(this.rail){c.fillStyle="#f2d33d";for(const train of this.rail.trains){const position=train.headPosition;c.beginPath();c.arc(position.x,position.z,3.2/s,0,Math.PI*2);c.fill();}}
    c.fillStyle="#7e939f";for(const vehicle of this.traffic.vehicles){c.beginPath();c.arc(vehicle.mesh.position.x,vehicle.mesh.position.z,2.1/s,0,Math.PI*2);c.fill();}c.fillStyle="#ff6e56";for(const incident of this.incidents.incidents){c.beginPath();c.arc(incident.marker.position.x,incident.marker.position.z,4/s,0,Math.PI*2);c.fill();}
    if(this.airport){c.fillStyle="#d7eef3";for(const aircraft of this.airport.aircraft){c.beginPath();c.arc(aircraft.mesh.position.x,aircraft.mesh.position.z,3.5/s,0,Math.PI*2);c.fill();}}if(this.police){c.fillStyle="#3388ff";for(const unit of this.police.units){c.beginPath();c.arc(unit.vehicle.mesh.position.x,unit.vehicle.mesh.position.z,3/s,0,Math.PI*2);c.fill();}}
    const playerFocus=this.player.inTrain?this.rail?.playerTrain?.headPosition:this.player.inBus?this.transit?.playerBus?.mesh.position:this.player.inAircraft?this.airport?.getPlayerFocus?.()?.position:this.player.position;c.fillStyle="#ffffff";c.beginPath();c.arc(playerFocus?.x??this.player.position.x,playerFocus?.z??this.player.position.z,5/s,0,Math.PI*2);c.fill();c.restore();
  }
}

export function makeToast(){const element=document.getElementById("toast");let timer;return message=>{element.textContent=message;element.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>element.classList.remove("show"),1800);};}
