import * as THREE from "three";

function instanceTransform(position,tangent,scale,vertical=0){const object=new THREE.Object3D();object.position.copy(position);object.position.y+=vertical;object.rotation.y=Math.atan2(tangent.x,tangent.z);object.scale.copy(scale);object.updateMatrix();return object.matrix.clone();}

export class RailSignalRenderer{
  constructor(scene,network,{interlocking=null,stationOperations=null}={}){this.scene=scene;this.network=network;this.interlocking=interlocking;this.stationOperations=stationOperations;this.group=new THREE.Group();this.group.name="rail-signals";scene.add(this.group);this.debugEnabled=false;this.junctionIndicators=[];this.build();}
  build(){
    const count=this.network.signals.length,postGeometry=new THREE.BoxGeometry(.14,3.6,.14),headGeometry=new THREE.BoxGeometry(.58,1.65,.34),plateGeometry=new THREE.BoxGeometry(.68,.28,.08),lampGeometry=new THREE.SphereGeometry(.13,8,6),postMaterial=new THREE.MeshStandardMaterial({color:0x34383a,roughness:.78}),headMaterial=new THREE.MeshStandardMaterial({color:0x171b1d,roughness:.7}),plateMaterial=new THREE.MeshStandardMaterial({color:0xd7d7cf,roughness:.72}),materials={red:new THREE.MeshStandardMaterial({color:0x551010,emissive:0xff2222,emissiveIntensity:2}),yellow:new THREE.MeshStandardMaterial({color:0x554510,emissive:0xffcc22,emissiveIntensity:2}),green:new THREE.MeshStandardMaterial({color:0x104d20,emissive:0x22ff55,emissiveIntensity:2})};
    this.posts=new THREE.InstancedMesh(postGeometry,postMaterial,count);this.heads=new THREE.InstancedMesh(headGeometry,headMaterial,count);this.plates=new THREE.InstancedMesh(plateGeometry,plateMaterial,count);this.red=new THREE.InstancedMesh(lampGeometry,materials.red,count);this.yellowLow=new THREE.InstancedMesh(lampGeometry,materials.yellow,count);this.yellowHigh=new THREE.InstancedMesh(lampGeometry,materials.yellow,count);this.green=new THREE.InstancedMesh(lampGeometry,materials.green,count);
    for(const mesh of[this.posts,this.heads,this.plates,this.red,this.yellowLow,this.yellowHigh,this.green]){mesh.instanceMatrix.setUsage([this.posts,this.heads,this.plates].includes(mesh)?THREE.StaticDrawUsage:THREE.DynamicDrawUsage);mesh.castShadow=false;mesh.receiveShadow=false;this.group.add(mesh);}
    this.plates.userData.identificationPlates=[];
    for(const [index,signal] of this.network.signals.entries()){this.posts.setMatrixAt(index,instanceTransform(signal.position,signal.tangent,new THREE.Vector3(1,1,1),1.8));this.heads.setMatrixAt(index,instanceTransform(signal.position,signal.tangent,new THREE.Vector3(1,1,1),3.25));this.plates.setMatrixAt(index,instanceTransform(signal.position,signal.tangent,new THREE.Vector3(1,1,1),2.12));this.plates.userData.identificationPlates.push(signal.identificationPlate);}
    this.posts.instanceMatrix.needsUpdate=true;this.heads.instanceMatrix.needsUpdate=true;this.plates.instanceMatrix.needsUpdate=true;this.buildJunctionVisuals();
    const debugMaterial=new THREE.MeshBasicMaterial({color:0x55b8ff,vertexColors:true,transparent:true,opacity:.82,depthWrite:false}),debugGeometry=new THREE.BoxGeometry(.12,5.4,.12);this.debugBoundaries=new THREE.InstancedMesh(debugGeometry,debugMaterial,this.network.blocks.length);this.debugBoundaries.visible=false;this.debugBoundaries.instanceMatrix.setUsage(THREE.StaticDrawUsage);this.debugBoundaries.instanceColor?.setUsage(THREE.DynamicDrawUsage);this.debugBoundaries.userData.blockIds=[];this.group.add(this.debugBoundaries);
    for(const [index,block] of this.network.blocks.entries()){const route=this.network.route(block.routeId),offset=route.trackOffsets?.[block.trackIndex]??0,progress=block.direction>0?block.startT:block.endT,position=route.curve.getPointAt(progress),tangent=route.curve.getTangentAt(progress).setY(0).normalize();position.add(new THREE.Vector3(-tangent.z,0,tangent.x).multiplyScalar(offset));this.debugBoundaries.setMatrixAt(index,instanceTransform(position,tangent,new THREE.Vector3(1,1,1),2.7));this.debugBoundaries.userData.blockIds.push(block.id);}
    this.debugBoundaries.instanceMatrix.needsUpdate=true;this.update();
  }
  buildJunctionVisuals(){
    const bladeGeometry=new THREE.BoxGeometry(.08,.08,7.2),bladeMaterial=new THREE.MeshStandardMaterial({color:0x92999c,roughness:.4,metalness:.72});
    for(const junction of this.network.junctions){const route=this.network.route("city")??this.network.routes[0],tangent=junction.tangent.clone().setY(0).normalize(),normal=junction.normal.clone().setY(0).normalize(),pointGroup=new THREE.Group();pointGroup.name=`${junction.id}-point-blades`;pointGroup.userData.junctionId=junction.id;
      for(const offset of route.trackOffsets??[-10.5,-3.5,3.5,10.5])for(const diverge of[-1,1]){const blade=new THREE.Mesh(bladeGeometry,bladeMaterial),position=junction.position.clone().addScaledVector(normal,offset+diverge*.22).addScaledVector(tangent,diverge*2.2);blade.position.copy(position);blade.position.y+=.26;blade.rotation.y=Math.atan2(tangent.x,tangent.z)+diverge*.035;blade.castShadow=false;blade.receiveShadow=false;pointGroup.add(blade);}this.group.add(pointGroup);
      const indicatorMaterial=new THREE.MeshStandardMaterial({color:0x451313,emissive:0xff2a22,emissiveIntensity:1.5,roughness:.58}),indicator=new THREE.Mesh(new THREE.BoxGeometry(.72,1.05,.32),indicatorMaterial),indicatorPosition=junction.position.clone().addScaledVector(normal,(route.trackOffset??10.5)+4.2);indicator.position.copy(indicatorPosition);indicator.position.y+=2.3;indicator.rotation.y=Math.atan2(tangent.x,tangent.z);indicator.name=`${junction.id}-route-indicator`;indicator.userData.junctionId=junction.id;this.group.add(indicator);this.junctionIndicators.push({junction,indicator});
    }
  }
  setLamp(mesh,index,signal,height,on){mesh.setMatrixAt(index,instanceTransform(signal.position,signal.tangent,new THREE.Vector3(on?1:.001,on?1:.001,on?1:.001),height));}
  update(){
    for(const [index,signal] of this.network.signals.entries()){const aspect=signal.aspect;this.setLamp(this.red,index,signal,3.62,aspect==="red");this.setLamp(this.yellowLow,index,signal,3.27,aspect==="yellow"||aspect==="double-yellow");this.setLamp(this.yellowHigh,index,signal,2.92,aspect==="double-yellow");this.setLamp(this.green,index,signal,2.57,aspect==="green");}for(const mesh of[this.red,this.yellowLow,this.yellowHigh,this.green])mesh.instanceMatrix.needsUpdate=true;
    for(const item of this.junctionIndicators){const active=Boolean(item.junction.lockedBy);item.indicator.material.color.setHex(active?0x174622:0x451313);item.indicator.material.emissive.setHex(active?0x2cff5a:0xff2a22);item.indicator.userData.routeId=item.junction.lockedRouteId;}
    if(this.debugEnabled){for(const [index,block] of this.network.blocks.entries()){const color=block.occupiedBy.size?new THREE.Color(0xff3b30):block.reservedBy?new THREE.Color(0xffcc33):new THREE.Color(0x55b8ff);this.debugBoundaries.setColorAt(index,color);}if(this.debugBoundaries.instanceColor)this.debugBoundaries.instanceColor.needsUpdate=true;this.debugBoundaries.userData.activeJunctionRoutes=[...(this.interlocking?.activeRoutes?.values()??[])].map(item=>item.route.id);this.debugBoundaries.userData.platformAllocations=[...(this.stationOperations?.allocations?.values()??[])];}
  }
  toggleDebug(){this.debugEnabled=!this.debugEnabled;this.debugBoundaries.visible=this.debugEnabled;this.update();return this.debugEnabled;}
}
